config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/browse', to: 'profiles#index'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  get '/profile/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile/:id', to: 'profiles#update', as: 'update_profile'

  get  '/filters', to: 'filters#edit', as: 'filters'
  post '/filters', to: 'filters#update'

  get '/account/new', to: 'users#new', as: 'new_account'
  post '/account', to: 'users#create', as: 'account'
  patch '/account', to: 'users#update'
  delete '/account', to: 'users#destroy'
  get '/account/settings', to: 'users#edit', as: 'account_settings'

  resources :conversations do
    resources :messages
  end
  
  
  get '/pull-requests/puller', to: 'likes#liker_index', as: 'puller_index'
  get '/pull-requests/pullee', to: 'likes#likee_index', as: 'pullee_index'
  post '/pull-requests', to: 'likes#create', as: 'create_pull_request'
  delete '/pull-requests', to: 'likes#destroy', as: 'close_pull_request'

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user
  has_many :answers
  has_many :questions, through: :answers
  has_attached_file :picture, styles: {
    thumb: '100x100>',
    square: '200x200',
    medium: '300x300>'
  }

  validates :about_me,  length:  { maximum: 140,
                                   too_long: "140 characters is the maximum allowed" },
                                   on: :update, allow_blank: :true

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates_format_of :github_link, with: /github\.((com)|(io))/, message: "url is not in proper format" , on: :update, allow_blank: :true

  def get_traits
    [user.languages, user.text_editors, user.skills, user.operating_systems, user.relationship_types].flatten
  end

end

app/controllers/profiles_controller.rb
require 'will_paginate/array'
class ProfilesController < ApplicationController
  before_action :load_preference_data, only: [:edit]
  def index
    if current_user
      filtered = Profile.where.not(id: [current_user.profile.id, current_user.get_likees].flatten).order(updated_at: :desc).select {|profile| get_gender.include?(profile.user.gender) && fits_filter(profile)}
      @profiles = filtered.paginate page: params[:page], per_page: 10
    else
      redirect_to login_path
    end
  end

  def show
    @profile = Profile.find_by(id: params[:id])
    if @profile
      @user = @profile.user
    else
      redirect_to login_path #change to 404 page path
    end
  end

  def edit
    @profile = Profile.find_by(id: params[:id])
    @user = current_user
    @user_languages = @user.languages
    @user_skills = @user.skills
    @user_relationship_types = @user.relationship_types

    if @profile != current_user.profile
      redirect_to edit_profile_path(current_user.profile)
    end
  end

  def update
    @user = User.find(current_user.id)
    ProfileUpdater.new.call(@user, params)
    redirect_to profile_path(@user.profile)
  end

  private

  def load_preference_data
    @genders = Gender.all
    @programming_languages = Language.all
    @text_editors = TextEditor.all
    @operating_systems = OperatingSystem.all
    @skills = Skill.all
    @relationship_types = RelationshipType.all
    @sexual_preferences = SexualPreference.all
    @sexual_orientations = SexualOrientation.all
  end

  def fits_filter(profile)
    return profile if !(get_user_filters & profile.get_traits).empty?
  end

  def get_gender
    pref = current_user.sexual_preference
    if pref.name == 'men'
      Gender.where(name: 'male')
    elsif pref.name == 'women'
      Gender.where(name: 'female')
    else
      Gender.all
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def separate_with_commas(object_array)
    object_array.pluck('name').join(', ')
  end
end

app/views/profiles/_profile_card.erb
<div class="row">
  <div class="thumbnail profile_card center align-left">
		<% if profile.picture_file_name %>
			<%= image_tag(profile.picture, class: "left profile_pic") %>
		<% else %>
			<%= image_tag("ninja.png", class: "left default-pic profile_pic") %>
		<% end %>
		<div class="profile_heading">
			<h3 class="left no-margin grey"><%= link_to(profile.user.first_name, profile_path(profile), class: "grey") %>, <%= profile.user.age %></h3>
		</div>
    <div class="caption profile_card_info ">
    	<p><%= profile.about_me %></p>
			<p><strong>Languages:</strong>
			<% if profile.user.languages.empty? %>
				N/A
			<% else %>
				<%= separate_with_commas(profile.user.languages) %>
			<% end %>
			</p>
			<p><strong>Text Editors:</strong>
			<% if profile.user.text_editors.empty? %>
				N/A
			<% else %>
				<%= separate_with_commas(profile.user.text_editors) %>
			<% end %>
			</p>
			<p><strong>Operating Systems:</strong>
			<% if profile.user.operating_systems.empty? %>
				N/A
			<% else %>
				<%= separate_with_commas(profile.user.operating_systems) %>
			<% end %>
			</p>
			<p><strong>Skills:</strong>
			<% if profile.user.skills.empty? %>
				N/A
			<% else %>
				<%= separate_with_commas(profile.user.skills) %>
			<% end %>
			</p>
			<p><strong>Looking for:</strong>
			<% if profile.user.relationship_types.empty? %>
				¯\_(ツ)_/¯
			<% else %>
				<%= separate_with_commas(profile.user.relationship_types) %>
			<% end %>
			</p>

			<%= link_to "new git log", conversations_path(sender_id: current_user.id, recipient_id: profile.user.id), method: :post, class: "btn btn-default" %>
			<% if current_user.pull_request_exists?(profile.user) %>
				<%= link_to "close pull request", close_pull_request_path(liked: profile.user), method: :delete, class: "btn btn-default" %>
			<% else %>
				<%= link_to "open pull request", create_pull_request_path(liked: profile.user), method: :post, class: "btn btn-default" %>
			<% end %>
    </div>
	</div>
</div>

app/views/profiles/edit.html.erb
<div class="add-body-margin">
	<%= form_for @user, :html => { :multipart => true, id: "edit-profile-form" }, url: update_profile_path, method: :patch do |f| %>

		<p>
		  <%= f.label :first_name %>
		  <%= f.text_field :first_name %>
		</p>
		<p>
		  <%= f.label :last_name %>
		  <%= f.text_field :last_name %>
		</p>
		<p>
			<%= f.label "Gender:" %><br>
			<%= f.select :gender_id, @genders.collect {|g| [g.name, g.id] }, {:selected => @user.gender_id} %>
		</p>

	  <%= fields_for :profile, @profile do |p| %>
	    <p>
	      <%= p.label :picture %>
	      <%= p.file_field :picture %>
	    </p>
	    <p>
	      <%= p.label :about_me %><br>
	      <%= p.text_area :about_me, id: 'profile_about_me' %> <br>
			</p>
	    <p>
	      <%= p.label :github_link %><br>
	      <%= p.text_field :github_link %>
			</p>
	  <% end %>

	  <fieldset>
	    <%= fields_for :languages, @programming_languages do |l| %>
	      <legend>Programming Languages:</legend>
	      <% @programming_languages.each do |programming_language| %>
	         <div class="inlineblock checkbox_cols">
	            <%= l.check_box programming_language.id, { checked: @user_languages.include?(programming_language) } %>
	            <%= l.label programming_language.name, for: "languages_#{programming_language.id}" %>
	        </div>
	      <% end %>
	    <% end %>
	  </fieldset>

	  <fieldset>
	    <%= fields_for :editors, @text_editors do |t| %>
				<legend><%= t.label "Text Editors:" %></legend>
				<% @text_editors.each do |text_editor| %>
	        <div class="inlineblock checkbox_cols">
						<%= t.check_box text_editor.id, {checked: @user.text_editors.include?(text_editor) } %>
						<%= t.label text_editor.name, for: "editors_#{text_editor.id}" %>
					</div>
				<% end %>
	  	<% end %>
	  </fieldset>

	  <fieldset>
	  	<%= fields_for :operating_systems, @operating_systems do |o| %>
	  			<legend>Operating Systems:</legend>
	  			<% @operating_systems.each do |operating_system| %>
	  				<div class="inlineblock checkbox_cols">
	  					<%= o.check_box operating_system.id, {checked: @user.operating_systems.include?(operating_system) } %>
	  					<%= o.label operating_system.name, for: "operating_systems_#{operating_system.id}" %>
	  				</div>
	  			<% end %>
	  	<% end %>
	  </fieldset>

	  <fieldset>
	  	<%= fields_for :skills, @skills do |s| %>
				<legend>Skills:</legend>
				<% @skills.each do |skill| %>
					<div class="inlineblock checkbox_cols">
						<%= s.check_box skill.id, { checked: @user_skills.include?(skill) } %>
						<%= s.label skill.name, for: "skills_#{skill.id}" %>
					</div>
				<% end %>
	  	<% end %>
	  </fieldset>

	  <p>
	    <%= f.label "Sexual Preference:" %><br>
	    <%= f.select :sexual_preference_id, @sexual_preferences.collect {|sp| [sp.name, sp.id]} %>
	  </p>

	  <p>
	    <%= f.label "Sexual Orientation:" %><br>
	    <%= f.select :sexual_orientation_id, @sexual_orientations.collect { |so| [so.name, so.id]  } %>
	  </p>

	  <%= f.submit %>
	<% end %>
</div>

app/views/profiles/index.html.erb
<div id="profile-browse" class="add-body-margin">
  <% @profiles.each do |profile| %>
  	<%= render partial: 'profiles/profile_card', locals: {profile: profile} %>
  <% end %>

  <div class="pagination_div"><%= will_paginate @profiles %></div>
</div>

app/views/profiles/show.html.erb
<article class="add-body-margin center show-profile">
  <section id="profile-show" class="left">
    <aside id="profile-aside" class="white-smoke-background-color padding-all-around">
    	<% if @profile.picture_file_name %>
    		<%= image_tag @profile.picture.url(:square, class: "profile-pic")%>
    	<% else %>
    		<%= image_tag("ninja.png", class: "profile-pic-padding-bottom profile-pic") %>
    	<% end %>
     <div class="username-age">
       <p class="lead">
         <%= @user.username %>
       </p>

       <p class="lead">
        <span id="age">Age:</span>
        <%= @user.age %> years old
      </p>

     <p class="lead">
        <% if @profile.user == current_user %>
          <%= link_to("Edit Profile", edit_profile_path(@profile), class: "btn btn-default") %>
        <% end %>
     </p>
    </div>
    </aside>
  </section>

 <section id="user-info">
  <section id="about-me">
   <div id="table-div">
     <table class="white-smoke-background-color padding-all-around">
      <tr>
        <th class="lead align-left"><h2>User Information</h2></th>
      </tr>
      <% if current_user == @user %>
        <tr>
          <td class="bold padding-left lead">First Name:</td>
          <td class="lead"><%= @user.first_name %></td>
        </tr>
        <tr>
          <td class="bold padding-left lead">Last Name:</td>
           <td class="lead"><%= @user.last_name %></td>
        </tr>
        <tr>
          <td class="bold padding-left lead">Birthday:</td>
          <td class="lead"><%= @user.birthday %></td>
        </tr>
        <tr>
          <td class="bold padding-left lead">Email:</td>
          <td class="lead"><%= @user.email %></td>
        </tr>
      <% end %>
      <tr>
        <td class="bold padding-left lead">Zip Code:</td>
        <td class="lead"><%= @user.zip_code %></td>
      </tr>
      <tr>
        <td class="bold padding-left lead">Gender:</td>
        <td class="lead"><%= @user.gender.name %></td>
      </tr>
      <tr>
        <td class="bold padding-left lead">Sexual Orientation:</td>
        <td class="lead"><%= @user.sexual_orientation.name %></td>
      </tr>
      <tr>
        <td class="bold padding-left lead">Sexual Preference:</td>
        <td class="lead"><%= @user.sexual_preference.name %></td>
      </tr>
      <tr>
       <td class="bold padding-left padding-bottom lead">Github Link:</td>
        <% if @user.profile.github_link.nil? %>
          <td class="lead">N/A</td>
        <% else %>
          <td class="lead"><%= link_to @user.profile.github_link, @user.profile.github_link, target: :_blank %></td>
        <% end %>
      </tr>
     </table>
    </div>
  </section>

  <div id="block">
   <section id="user-skills" class="white-smoke-background-color padding-all-around inlineblock">

    <div class="overflow-hidden">
      <% unless @user.profile.about_me.nil? %>
        <div class="left help-image"><%= image_tag "user.jpg", class: "user_skills_imgs" %></div>
        <div class="left help">
          <h2 class="user-skills-header">About Me</h2>
          <div class="lead"><%= @user.profile.about_me %></div>
        </div>
      <% end %>
   </div>

    <div class="overflow-hidden">
       <div class="left help-image"><%= image_tag "code.jpg", class: "user_skills_imgs" %></div>
       <div class="left help">
         <h2 class="user-skills-header" >Programming Languages</h2>
            <% @user.languages.each do |language| %>
              <div class="lead user-pills inlineblock"><%= language.name %></div>
            <% end %>
       </div>
    </div>

    <div class="overflow-hidden">
      <div class="left help-image"><%= image_tag "text_editor.jpg", class: "user_skills_imgs" %></div>
      <div class="left help">
        <h2 class="user-skills-header">Text Editors</h2>
          <% @user.text_editors.each do |editor| %>
           <div class="lead user-pills inlineblock"><%= editor.name %></div>
          <% end %>
    </div>
    </div>

    <div class="overflow-hidden">
     <div class="left help-image"><%= image_tag "system_information.jpg", class: "user_skills_imgs" %></div>
      <div class="left help">
        <h2 class="user-skills-header">Operating Systems</h2>
          <% @user.operating_systems.each do |operating_system| %>
            <div class="lead user-pills inlineblock"><%= operating_system.name %></div>
          <% end %>
      </div>
    </div>

    <div class="overflow-hidden">
      <div class="left help-image"><%= image_tag "skill.jpg", class: "user_skills_imgs" %></div>
      <div class="left help">
        <h2 class="user-skills-header">Skills</h2>
          <% @user.skills.each do |skill| %>
            <div  class="lead user-pills inlineblock"><%= skill.name %></div>
          <% end %>
      </div>
    </div>

     </section>
   </section>
 </div>
</article>