config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/browse', to: 'profiles#index'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  get '/profile/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile/:id', to: 'profiles#update', as: 'update_profile'

  get  '/filters', to: 'filters#edit', as: 'filters'
  post '/filters', to: 'filters#update'

  get '/account/new', to: 'users#new', as: 'new_account'
  post '/account', to: 'users#create', as: 'account'
  patch '/account', to: 'users#update'
  delete '/account', to: 'users#destroy'
  get '/account/settings', to: 'users#edit', as: 'account_settings'

  resources :conversations do
    resources :messages
  end
  
  
  get '/pull-requests/puller', to: 'likes#liker_index', as: 'puller_index'
  get '/pull-requests/pullee', to: 'likes#likee_index', as: 'pullee_index'
  post '/pull-requests', to: 'likes#create', as: 'create_pull_request'
  delete '/pull-requests', to: 'likes#destroy', as: 'close_pull_request'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile
  belongs_to :gender
  belongs_to :sexual_orientation
  belongs_to :sexual_preference

  has_many :user_seekings
  has_many :relationship_types, through: :user_seekings

  has_many :user_filters
  has_many :filters, through: :user_filters

  has_many :user_text_editors
  has_many :text_editors, through: :user_text_editors
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :user_operating_systems
  has_many :operating_systems, through: :user_operating_systems
  has_many :user_languages
  has_many :languages, through: :user_languages


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, presence: true, allow_nil: true, length: {minimum: 8, maximum: 25}
  validates :username, presence: true, uniqueness: true
  validates :zip_code, presence: true
  validates :birthday, presence: true
  validates :email, presence: true, uniqueness: true

  validates_format_of :email, with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def age
    (Date.today - birthday).to_i / 365
  end

  def get_likees
    Like.where(liker_id: id).map(&:liked)
  end

  def get_likers
    Like.where(liked_id: id).map(&:liker)
  end

  def pull_request_exists?(user)
    get_likees.include?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render template: 'temp_index'
  end

  def new
    if current_user
      redirect_to edit_profile_path(current_user.profile)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    @user.gender = Gender.find_by(id: params[:gender_id])
    @user.sexual_orientation = SexualOrientation.find_by(id: params[:sexual_orientation_id])
    @user.sexual_preference = SexualPreference.find_by(id: params[:sexual_preference_id])

    if @user.save
      session[:user_id] = @user.id
      Profile.create(user: @user)
      Filter.all.each do |filter|
        @user.user_filters.create(filter: filter)
      end
      redirect_to edit_profile_path(@user.profile)
    else
      @errors = @user.errors.full_messages
      render template: 'users/new'
    end
  end

  def show
    if current_user
      @user = User.find_by(id: params[:id])
      if @user.nil? # change to 404
        redirect_to root_path
      else
        redirect_to profile_path(@user.profile)
      end
    else
      redirect_to login_path
    end
  end

  def edit
    current_user ? (@user = current_user) : (redirect_to login_path)
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to profile_path(@user.profile)
    else
      @errors = @user.errors.full_messages
      render template: 'users/edit'
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation, :birthday, :gender_id, :sexual_orientation_id, :sexual_preference_id, :zip_code)
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/edit.html.erb
<div class="add-body-margin">
  <h1 class="center text-center">Account Settings</h1>

  <%= form_for @user, url: account_path, method: :patch do |f| %>
    <div class="input-group">
      <%= f.label :username, class: "input-group-addon" %>
      <%= f.text_field :username, class: "form-control", validate: true %>
    </div>
    <div class="input-group">
      <%= f.label :email, class: "input-group-addon" %>
      <%= f.text_field :email, class: "form-control", validate: true %>
    </div>
    <div class="input-group">
      <%= f.label :password, class: "input-group-addon" %>
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
    </div>
    <div class="input-group">
      <div class="input-group-addon"></div>
      <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control" %>
    </div>
    <div class="center input-group">
      <%= f.submit :submit, class: "submit btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/users/login.html.erb
<div class="add-body-margin">
  <h1 class="center text-center">Login</h1>

  <%= form_for :user, url: login_path do |f| %>
    <div class="input-group">
      <%= f.label :username, class: "input-group-addon" %>
      <%= f.text_field :username, class: "form-control" %>
  	</div>
  	<div class="input-group">
      <%= f.label :password, class: "input-group-addon" %>
      <%= f.password_field :password, class: "form-control" %>
  	</div>
  	<div class="center input-group">
      <%= f.submit :submit, class: "submit btn btn-default" %>
  	</div>
  <% end %>

  <% if @errors %>
    <ul>
    <% @errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="add-body-margin">
  <h1 class="center align-center">Create an Account</h1>

  <%= form_for @user, url: account_path do |f| %>
    <div class="input-group">
      <%= f.label :first_name, class: "input-group-addon" %>
      <%= f.text_field :first_name, class: "form-control", validate: true %>
  	</div>
    <div class="input-group">
      <%= f.label :last_name, class: "input-group-addon" %>
      <%= f.text_field :last_name, class: "form-control" %>
  	</div>
    <div class="input-group">
      <%= f.label :email, class: "input-group-addon" %>
      <%= f.email_field :email, class: "form-control" %>
  	</div>
    <div class="input-group">
      <%= f.label :username, class: "input-group-addon" %>
      <%= f.text_field :username, class: "form-control" %>
  	</div>
  	<div class="input-group">
      <%= f.label :password, class: "input-group-addon" %>
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
  	</div>
  	<div class="input-group">
      <div class="input-group-addon"></div>
      <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control" %>
  	</div>
  	<div class="input-group">
  	  <%= f.label :birthday %><br>
  	  <%= f.date_select :birthday, start_year: Date.today.year - 99, end_year: Date.today.year - 18, default: {year: Date.today.year - 18} %>
  	</div>
  	<div class="input-group">
  	  <%= label_tag :gender_id, "Gender" %><br>
  	  <%= select_tag(:gender_id, options_for_select(Gender.all.map{ |gender| [gender.name, gender.id]} )) %>
  	</div>
  	<div class="input-group">
  	  <%= label_tag :sexual_orientation_id, "Sexual orientation" %><br>
  	  <%= select_tag(:sexual_orientation_id, options_for_select(SexualOrientation.all.map{|sexual_orientation| [sexual_orientation.name, sexual_orientation.id]})) %>
  	</div>
  	<div class="input-group">
  	  <%= label_tag :sexual_preference_id, "Sexual preference" %><br>
  	  <%= select_tag(:sexual_preference_id, options_for_select(SexualPreference.all.map{|sexual_preference| [sexual_preference.name, sexual_preference.id]})) %>
  	</div>
  	<div class="input-group">
  	  <%= f.label :zip_code, class: "input-group-addon" %>
  	  <%= f.text_field :zip_code, class: "form-control" %>
  	</div>
  	<div class="center input-group">
  	  <%= f.submit :submit, class: 'submit btn btn-default' %>
  	</div>
  <% end %>
</div>

app/views/users/show.html.erb
User: <%= @user.username %>
<h4>View your <%= link_to "Profile",  profile_path(@user) %></h4>
<h4>Edit your <%= link_to "Profile", edit_profile_path(@user) %></h4>

<div>
  <p>
    <%= @user.username %>
    <%= @user.first_name %>
    <%= @user.last_name %>
    <%= @user.age %> years old
  </p>
</div>

<div>
  <p>
    <%= @user.email %>
    <%= @user.zip_code %>
  </p>
</div>

<div>
  <p>
    <%= @user.sexual_orientation.name %> <%= @user.gender.name %> looking for  <%= @user.sexual_preference.name %>
  </p>
</div>