config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/browse', to: 'profiles#index'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  get '/profile/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile/:id', to: 'profiles#update', as: 'update_profile'

  get  '/filters', to: 'filters#edit', as: 'filters'
  post '/filters', to: 'filters#update'

  get '/account/new', to: 'users#new', as: 'new_account'
  post '/account', to: 'users#create', as: 'account'
  patch '/account', to: 'users#update'
  delete '/account', to: 'users#destroy'
  get '/account/settings', to: 'users#edit', as: 'account_settings'

  resources :conversations do
    resources :messages
  end
  
  
  get '/pull-requests/puller', to: 'likes#liker_index', as: 'puller_index'
  get '/pull-requests/pullee', to: 'likes#likee_index', as: 'pullee_index'
  post '/pull-requests', to: 'likes#create', as: 'create_pull_request'
  delete '/pull-requests', to: 'likes#destroy', as: 'close_pull_request'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Git Committed</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
	<%= javascript_include_tag 'rails.validations' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
        <img src="http://res.cloudinary.com/svcastaneda/image/upload/c_scale,e_green:40,q_40,w_40/v1456435913/gitcommitted_zclsx5.png" class= 'logo left')>
				<%= link_to("Git Committed", root_path, class: 'navbar-brand logo no-margin ') %>
	    </div>
	    <div class="collapse navbar-collapse navbar-right" id="myNavbar">
	      <ul class="nav navbar-nav">
	        <li><%= link_to("home", root_path) %></li>
					<% if current_user %>
						<li><%= link_to("browse", browse_path) %></li>
						<li><%= link_to("git logs", conversations_path) %></li>
		        <li class="dropdown">
		          <a class="dropdown-toggle" data-toggle="dropdown" href="#">pull requests<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to("git stashes", puller_index_path) %></li>
								<li><%= link_to("open requests", pullee_index_path) %></li>
							</ul>
						</li>
					<% end %>
	        <li class="dropdown">
						<% if current_user %>
		          <a class="dropdown-toggle" data-toggle="dropdown" href="#">account<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to("profile", profile_path(current_user.profile)) %></li>
								<li><%= link_to("filters", filters_path) %></li>
		            <li><%= link_to("settings", account_settings_path) %></li>
		            <li><%= link_to("logout", logout_path, method: :delete) %></li>
							</ul>
						<% else %>
		          <li><%= link_to("login", login_path) %></li>
							<li><%= link_to("register", new_account_path) %></li>
						<% end %>
          </ul>
	      </ul>
	  </div>
	</nav>
<div class="content">
	<%= yield %>
</div>
</body>
</html>